export const FETCH_MOVIE_REQUEST = 'FETCH_MOVIE_REQUEST';
export const FETCH_MOVIE_SUCCESS = 'FETCH_MOVIE_SUCCESS';
export const FETCH_MOVIE_FAILURE = 'FETCH_MOVIE_FAILURE';

export const FETCH_MOVIES_REQUEST = 'FETCH_MOVIES_REQUEST';
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const FETCH_MOVIES_FAILURE = 'FETCH_MOVIES_FAILURE';

export const ADD_MOVIE = 'ADD_JOKE';
export const REMOVE_MOVIE = 'REMOVE_JOKE';
export const FILTER_MOVIES = 'FILTER_MOVIES';
export const CHANGE_CATEGORY = 'CHANGE_CATEGORY';
